model: anthropic:claude-3-5-sonnet-20240620

clients:
- type: claude
  name: anthropic
  models:
     - name: claude-3-5-sonnet-20240620 
       max_input_tokens: 200000 
       max_output_tokens: 8192 
       require_max_tokens: true 
       input_price: 3 
       output_price: 15 
       supports_vision: true 
       supports_function_calling: true 
